# Generated by Django 4.1.5 on 2023-01-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("numbers", models.CharField(max_length=100)),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.CharField(max_length=100),
        ),
    ]
